### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by davidromani** [somenxavier/powered-by-somenergia#5]
There is a missing resource (404) here http://somenxavier.github.io/powered-by-somenergia/

<img width="1214" alt="captura de pantalla 2015-09-28 a les 9 02 30" src="https://cloud.githubusercontent.com/assets/698779/10129558/c7d887ee-65bf-11e5-8a55-a4681d68c9cf.png">

**Comment by somenxavier** [comment]
I have no this error. All is fine except:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
getPreventDefault() està en desús. Utilitzeu el mètode defaultPrevented. jquery.min.js:3:0
```

Strange. Try again.
Tested against Firefox 40.0.3

**Comment by davidromani** [comment]
Tested with Firefox 40.0.3 and same error fired. Maybe you have something cached in your local browser environment.

**Comment by somenxavier** [comment]
It works for me
![captura_2015-09-29_09-09-47](https://cloud.githubusercontent.com/assets/89915/10157389/fd990eba-6689-11e5-80cc-46287635d833.png)

Perhaps @vokimon  could confirm that.

**Comment by davidromani** [comment]
I've a retina display, so maybe, my broswer is requesting for marker-icon-**2x**.png

**Comment by somenxavier** [comment]
Try again: https://github.com/somenxavier/powered-by-somenergia/commit/b2f3d915f12bacff9e66b8caca0a2818ec1ea31e

**Comment by davidromani** [comment]
I works, well done! :+1:

**Comment by somenxavier** [comment]
Thanks to you
